config/routes.rb
Chupandero::Application.routes.draw do

  resources :bars

  resources :registers

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
  
  get 'tags/:tag', to: 'bars#index', as: :tag

  get "static_pages/contact"
  
  root :to => 'static_pages#registro'
  match "home", to: 'static_pages#home'
  
  get '/map', to: 'bars#map'
  

end

app/models/bar.rb
class Bar < ActiveRecord::Base
  attr_accessible :address, :description, :horary, :image1, :image2, :logo, :name, :phone,
                  :promo, :page, :email, :geo_address, :latitude, :longitude, :tag_list
  
  geocoded_by :geo_address
  after_validation :geocode
  acts_as_taggable

end

app/models/register.rb
class Register < ActiveRecord::Base
  attr_accessible :email
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/bars_controller.rb
class BarsController < ApplicationController
  # GET /bars
  # GET /bars.json
  before_filter :authenticate_user!, except: [:index, :show]

  def index
    @bars = Bar.all
    @tag_list = @bars.map do |u|
      {:tag => u.tag_list}
    end 
    json = @tag_list
    respond_to do |format|
      format.html # index.html.erb
      format.json  { render :json => {:bar => @bars, 
                                  :tags => json }}
    end
  end

  # GET /bars/1
  # GET /bars/1.json
  def show
    @bar = Bar.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bar }
    end
  end

  # GET /bars/new
  # GET /bars/new.json
  def new
    @bar = Bar.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bar }
    end
  end

  # GET /bars/1/edit
  def edit
    @bar = Bar.find(params[:id])
  end

  # POST /bars
  # POST /bars.json
  def create
    @bar = Bar.new(params[:bar])

    respond_to do |format|
      if @bar.save
        format.html { redirect_to @bar, notice: 'Bar was successfully created.' }
        format.json { render json: @bar, status: :created, location: @bar }
      else
        format.html { render action: "new" }
        format.json { render json: @bar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bars/1
  # PUT /bars/1.json
  def update
    @bar = Bar.find(params[:id])

    respond_to do |format|
      if @bar.update_attributes(params[:bar])
        format.html { redirect_to @bar, notice: 'Bar was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @bar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bars/1
  # DELETE /bars/1.json
  def destroy
    @bar = Bar.find(params[:id])
    @bar.destroy

    respond_to do |format|
      format.html { redirect_to bars_url }
      format.json { head :no_content }
    end
  end
  
  def map
     @bar = Bar.find(params[:bar_id])
  end
end

app/controllers/registers_controller.rb
class RegistersController < ApplicationController
  # GET /registers
  # GET /registers.json
  def new
    @register = Register.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @register }
    end
  end

  
  # POST /registers
  # POST /registers.json
  def create
     @register = Register.new(params[:register])
     if @register.save
        UserMailer.signup_confirmation(@register).deliver
        redirect_to root_path
     else
        render :new
     end
  end
  

 

  # DELETE /registers/1
  # DELETE /registers/1.json
  def destroy
    @register = Register.find(params[:id])
    @register.destroy

    respond_to do |format|
      format.html { redirect_to registers_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
   
  def home
  end

  def contact
  end
  
  def registro
     @register = Register.new
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   
   def new
      @user = User.new
   end
   
   def create
      @user = User.new(params[:user])
      if @user.save
         UserMailer.signup_confirmation(@user).deliver
         redirect_to root_path
      else
         render :new
      end
   end
   
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bars_helper.rb
module BarsHelper
end

app/helpers/registers_helper.rb
module RegistersHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/bars/_form.html.erb
<div class="container">
	<div class="row">
		<div class="span12">
			<div class="span8 offset2">
				<%= form_for(@bar) do |f| %>
				  <% if @bar.errors.any? %>
				    <div id="error_explanation">
				      <h2><%= pluralize(@bar.errors.count, "error") %> prohibited this bar from being saved:</h2>
				      <ul>
				      <% @bar.errors.full_messages.each do |msg| %>
				        <li><%= msg %></li>
				      <% end %>
				      </ul>
				    </div>
				  <% end %>

				  <div class="field">
				    <%= f.label :Nombre_del_bar %>
				    <%= f.text_field :name %>
				  </div>
				  <div class="field">
				    <%= f.label :Imagen_del_logo %>
				    <%= f.text_field :logo %>
				  </div>
				  <div class="field">
				    <%= f.label :Reseña %>
				    <%= f.text_area :description, class: "span6", rows: 6 %>
				  </div>
				  <div class="field">
				    <%= f.label :Direccion %>
				    <%= f.text_area :address, class: "span6", rows:2 %>
				  </div>
				  <div class="field">
				    <%= f.label :Email_del_bar %>
				    <%= f.text_field :email %>
				  </div>
				  <div class="field">
				    <%= f.label :Website %>
				    <%= f.text_field :page	 %>
				  </div>
				  <div class="field">
				    <%= f.label :Telefono %>
				    <%= f.text_area :phone, class: "span4", rows:2 %>
				  </div>
				  <div class="field">
				    <%= f.label :Horarios %>
				    <%= f.text_area :horary, class: "span6", rows:2 %>
				  </div>
				  <div class="field">
				    <%= f.label :Promo %>
				    <%= f.text_area :promo, class: "span6", rows:3 %>
				  </div>
				  <div class="field">
  					<%= f.label :tag_list, "Tags (separated by commas)" %><br />
  					<%= f.text_field :tag_list %>
				  </div>
				  <div class="field">
				    <%= f.label :image1 %>
				    <%= f.text_field :image1 %>
				  </div>
				  <div class="field">
				    <%= f.label :image2 %>
				    <%= f.text_field :image2 %>
				  </div>
				 <div class="field">
				    <%= f.label :Direccion_en_Google %>
				    <%= f.text_area :geo_address, class: "span4", rows: 2 %>
				  </div>
				  <div class="field">
				    <%= f.label :Latitude %>
				    <%= f.text_area :latitude, class: "span4", rows: 2  %>
				  </div>
				  <div class="field">
				    <%= f.label :Longitude %>
				    <%= f.text_area :longitude, class: "span4", rows: 2  %>
				  </div>
				  <div class="actions">
				    <%= f.submit %>
				  </div>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/bars/_map.html.erb
<div class="modal-chupandero">
  <div style="float:right">
  	<button type="button" class="close-button" data-dismiss="modal" aria-hidden="true">X</button>
  </div>
  <div class="modal_body">
	<div class="span8">
		<iframe width="825" height="550" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com.mx/maps?f=q&amp;source=s_q&amp;hl=es&amp;geocode=&amp;q=Puebla&amp;aq=&amp;sll=23.554132,-102.6205&amp;sspn=19.738439,34.40918&amp;ie=UTF8&amp;hq=&amp;hnear=Circuito+Juan+Pablo+II,+Puebla&amp;ll=<%= @bar.latitude%>,<%= @bar.longitude %>&amp;spn=0.022397,0.038581&amp;t=m&amp;z=18&amp;output=embed&iwloc=near"></iframe>
	</div>
  </div>
</div>

app/views/bars/edit.html.erb
<h1>Editing bar</h1>

<%= render 'form' %>

<%= link_to 'Show', @bar %> |
<%= link_to 'Back', bars_path %>

app/views/bars/index.html.erb
<h1>Listing bars</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Logo</th>
    <th>Description</th>
    <th>Address</th>
    <th>Phone</th>
    <th>Horary</th>
    <th>Promo</th>
    <th>Image1</th>
    <th>Image2</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @bars.each do |bar| %>
  <tr>
    <td><%= bar.name %></td>
    <td><%= bar.logo %></td>
    <td><%= bar.description %></td>
    <td><%= bar.address %></td>
    <td><%= bar.phone %></td>
    <td><%= bar.horary %></td>
    <td><%= bar.promo %></td>
    <td><%= bar.image1 %></td>
    <td><%= bar.image2 %></td>
    <td><%= link_to 'Show', bar %></td>
    <td><%= link_to 'Edit', edit_bar_path(bar) %></td>
    <td><%= link_to 'Destroy', bar, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Bar', new_bar_path %>

app/views/bars/map.js.erb
var y = window.pageYOffset;
document.documentElement.style.overflowY = "hidden";

window.onscroll = function(){
	window.scroll(0, y);
};
$('#modal-id').fadeIn('fast');
$('#modal-id').html("<%= escape_javascript(render :partial => 'map', :object => @bar) %>");
$('#modal-id').click(function(){
	window.onscroll = null;
	document.documentElement.style.overflowY = "scroll";
});
$(document).keyup(function(e) {
  if (e.keyCode == 27) { $('#modal-id').show();
	window.onscroll = null;
	document.documentElement.style.overflowY = "scroll";
   }   // esc
});

$('.close-button').click(function(){
	$('#modal-id').fadeOut('fast');
});

app/views/bars/new.html.erb
<h1>New bar</h1>

<%= render 'form' %>

<%= link_to 'Back', bars_path %>

app/views/bars/show.html.erb
<% content_for :meta do %>
	<% meta :keywords => %w(chupandero cerveza puebla amigos) %>
	<% meta [:property => "og:image", :content => "https://launchrock-assets.s3.amazonaws.com/facebook-files/OM38ZA8H_1361245291491.jpg?_=1"] %>
	<% meta [:property => "og:description", :content => "Descubre los mejores bares de Puebla - chupandero.com"] %>
	<% meta [:property => "og:type", :content => "website"] %>
	<% meta [:property => "og:title", :content => " Chupandero - Descubre los mejores bares de Puebla"] %>
	<% meta [:property => "og:url", :content => "http://chupandero.com/bars/#{@bar.id}"] %>
<% end %>

	<div class="row-fluid">
		<div class="span12">
				<div class="span3" id="main_menu">
				<div class="main_logo">
					<%= image_tag(@bar.logo, style:"width:327px; height: 300px")%>
					<!-- <%= image_tag "http://maps.google.com/maps/api/staticmap?size=400x400&sensor=false&zoom=16&markers=#{@bar.latitude}%2C#{@bar.longitude}"%> -->
				<!--	<iframe width="425" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com.mx/maps?f=q&amp;source=s_q&amp;hl=es&amp;geocode=&amp;q=Puebla&amp;aq=&amp;sll=23.554132,-102.6205&amp;sspn=19.738439,34.40918&amp;ie=UTF8&amp;hq=&amp;hnear=Circuito+Juan+Pablo+II,+Puebla&amp;ll=<%= @bar.latitude%>,<%= @bar.longitude %>&amp;spn=0.022397,0.038581&amp;t=m&amp;z=14&amp;output=embed&iwloc=near"></iframe>-->
				</div>
				<hr style="margin:0">
				<div style="text-align:center" id="bar_title">
					<%= @bar.name %>
				</div>
				<hr style="margin:0">
				<p id="bar_info">
					<i class="icon-map-marker icon-white"></i>
					<%= @bar.address%>
					<br/>
					<%= link_to "Ver mapa", map_path(:bar_id => @bar.id), {:id => "modal", :rel => "tab", :remote => true, 'data-controls-modal' =>  "modal-window", 'data-backdrop' => true, 'data-keyboard' => true} %>
				</p>
				<p id="bar_info">
					<i class="icon-tag icon-white"></i>
					<%= link_to @bar.page, @bar.page %>
					<br/>
				</p>
				<p id="bar_info">
					<i class="icon-envelope icon-white"></i>
					<%= link_to @bar.email, "#" %>
					<br/>
				</p>
				<p id="bar_info">
					<i class="icon-time icon-white"></i>
					Horarios:<br/> <%= @bar.horary %>
				</p>
				<p id="bar_info">
					<i class="icon-info-sign icon-white"></i>
					Teléfono: <br/> <%= @bar.phone %>
				</p>
			</div>
			<div class="row-fluid">
				<div style="margin-left: -44px; margin-top: -1px;">
					<div class="span9 offset3">
						<p id="notice"><%= notice %></p>
						<div id="myCarousel" style="height:378px; margin:0; box-shadow: 0px 6px 15px 2px; -webkit-box-shadow: 2px 6px 15px 1px;" class	="carousel slide">
								  <!-- Carousel items -->
						   <div class="carousel-inner">
							<div class="active item"><%= image_tag(@bar.image1, style: "max-height:378px; max-width: 900px ")%></div>
						    <div class="item"><%= image_tag(@bar.image2,  style: "max-height:378px; max-width: 900px")%></div>
						  </div>
						  <!-- Carousel nav -->
						  <a style="display:none" class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
						  <a style="display:none" class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
						</div>
						<div class="span10">
							<h1 class="promo" >
								"<%= @bar.promo%>"
							</h1>
							<p>Tags: <%= @bar.tag_list %></p>
							<div class="span9 offset1">
								<p class="resena">
									<%= @bar.description %>
								</p>
								<hr>
								<br>
								<div class="fb-comments" data-href="http://chupandero.com/bars/<%= @bar.id %>" data-width="650" data-num-posts="10"></div>
							</div>
						</div>
						<%= render 'layouts/footer' %>
					</div>
				</div>
			</div>
		</div>
	</div>
<div id="fb-root"></div>
<script>

(function(d, s, id) {
	  var js, fjs = d.getElementsByTagName(s)[0];
	  if (d.getElementById(id)) return;
	  js = d.createElement(s); js.id = id;
	  js.src = "//connect.facebook.net/es_LA/all.js#xfbml=1&appId=458747400865661";
	  fjs.parentNode.insertBefore(js, fjs);
	}(document, 'script', 'facebook-jssdk'));	
	
	$(function(){
		$('.carousel').carousel({
	  		interval: 3000,
			pause: 'hover'
		});
	});
</script>

app/views/layouts/_footer.html.erb
<div class="span10">
	<div id="footer">
		<div class="span10">
			<p id="links">
				<%= link_to "Sobre el chupandero", "#"%>
				<%= link_to "Equipo", "#" %>
				<%= link_to "Terminos de uso", "#" %>
				<%= link_to "Contacto", "#" %>
			</p>
	</div>
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
			<%= link_to image_tag('http://i1321.photobucket.com/albums/u543/Julio_Ahuactzin/logo_zps39cb8c6a.png', style: "width:120px"), root_path, class: "brand" %>
        <!--  <div class="nav-collapse collapse">
            <ul class="nav">
              <li>
					<a><i class="icon-glass icon-white"></i>Bares destacados</a>
              </li>
              <li>
                	<a><i class="icon-info-sign icon-white"></i>Contacto</a>
              </li>
            </ul> -->
			 <ul class="nav pull-right">
				<% if user_signed_in? %>
                 <li class="divider-vertical"></li>
                 <li class="dropdown">
                   <a href="#" class="dropdown-toggle" data-toggle="dropdown">Sesion de <strong><%= current_user.email %></strong> <b class="caret"></b></a>
                   <ul class="dropdown-menu">
                     <li><%= link_to "Editar", edit_user_registration_path %></li>
                     <li><%= link_to "Cerrar sesion", destroy_user_session_path, method: :delete %></li>
                   </ul>
                 </li>
				<% else %>
				<li><%= link_to "Registrarse", new_user_registration_path %></li>
				<li class="divider-vertical"></li>
                <li><%= link_to "Iniciar sesión", new_user_session_path %></li>
				<% end %>
			  </ul>
          </div>
        </div>
      </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chupandero - Encuentra los mejores bares de la Ciudad de Puebla</title>
  <%= metamagic :title => "Chupandero", :description => "Descubre los mejores bares de Puebla", :keywords => %w(keyword1 keyword2 keyword3) %>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header' %>
	<%= yield %>
	<div id="modal-id"></div>
    
</body>
</html>

app/views/registers/_form.html.erb
<%= form_for(@register) do |f| %>
  <% if @register.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@register.errors.count, "error") %> prohibited this register from being saved:</h2>

      <ul>
      <% @register.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/registers/edit.html.erb
<h1>Editing register</h1>

<%= render 'form' %>

<%= link_to 'Show', @register %> |
<%= link_to 'Back', registers_path %>

app/views/registers/index.html.erb
<h1>Listing registers</h1>

<table>
  <tr>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @registers.each do |register| %>
  <tr>
    <td><%= register.email %></td>
    <td><%= link_to 'Show', register %></td>
    <td><%= link_to 'Edit', edit_register_path(register) %></td>
    <td><%= link_to 'Destroy', register, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Register', new_register_path %>

app/views/registers/new.html.erb
<h1>New register</h1>

<%= render 'form' %>

<%= link_to 'Back', registers_path %>

app/views/registers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Email:</b>
  <%= @register.email %>
</p>


<%= link_to 'Edit', edit_register_path(@register) %> |
<%= link_to 'Back', registers_path %>

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/registro.html.erb
<% content_for :meta do %>
	<% meta :keywords => %w(chupandero cerveza puebla amigos) %>
	<% meta [:property => "og:image", :content => "https://launchrock-assets.s3.amazonaws.com/facebook-files/OM38ZA8H_1361245291491.jpg?_=1"] %>
	<% meta [:property => "og:description", :content => "Descubre los mejores bares de Puebla - chupandero.com"] %>
	<% meta [:property => "og:type", :content => "website"] %>
	<% meta [:property => "og:title", :content => " Chupandero - Descubre los mejores bares de Puebla"] %>
	<% meta [:property => "og:url", :content => "http://chupandero.com"] %>
<% end %>

<!-- Begin LaunchRock Widget -->
<div id="lr-widget" rel="OM38ZA8H"></div>
<script type="text/javascript" src="//ignition.launchrock.com/ignition-current.min.js"></script>
<!-- End LaunchRock Widget -->